### ISSUE TITLE
[Feature request] Object filtering -> array

### ISSUE THREAD

**Issue by matthew-dean** [nickofthyme/object-remap#14]
I'd like to do something like:
```js
{
  one: true
  two: false
  three: true
  foo: false 
}
```
...and map this to:
```js
['one', 'three']
```
In other words, object entry filtering -> array. This seems like a good project to add this feature.

**Comment by nickofthyme** [comment]
Sorry for the delay, my notifications where disabled for this repo.

That could be a good feature, though I'm not exactly sure how it would work. It's been a while since I touched this or GitHub actions, so I might be missing something.

To be precise, I'm not sure how this action can facilitate filtering the arrays within the [expression](https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions). Currently, doing something like...

```yml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Get mock test object
        id: mock
        run: echo "::set-output name=json::{\"one\":1,\"two\":{\"one\":1},\"three\":{\"two\":{\"one\":1}},\"numbers\":[1,2,3],\"array\":[{\"test\":\"key1\",\"deeper\":{\"deep\":1}},{\"test\":\"key2\"}]}"
      - name: Complex values
        id: test # used to access output in other steps
        uses: nickofthyme/object-remap@v1
        with:
          test.*.key: ${{ fromJSON(steps.mock.outputs.json).array.*.test }} # value is just ['key1', 'key2`]
```

The value in `${{ }}` is purely handled by GitHub actions parser, which does not have a filter function in their [provided functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions). The only exception to this is to apply the _global_ [input options](https://github.com/nickofthyme/object-remap#inputs) but these apply to **all** values in the final output whereas this proposal could be applied at any level.

I think the best approach for this might be to add a new top-level `__filter` option, something like...

```yml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Simple
        id: test
        uses: nickofthyme/object-remap@v1
        with:
          __filter:
            _root: true
            nested:[1,3]
          one: true
          two: false
          three: true
          foo: false
          nested.one: 1
          nested.two: 2
          nested.three: 3
```

The the `__filter` is saying give me anything at the `_root` level that is equal to `true` and anything at the `nested` level that is `1` or `3`. Any literal key defined in `__filter` would override a previous filter, in this case key `nested` would not be checked for `true`. So the above result of `steps.test.outputs.json` would be...

```json
{
  "_root": ["one", "three"],
  "nested": ["bar"]
}
```

Not sure if _filter_ is the right term for this as it just returns the keys matching the values, seems more like a _find_. I'm also not sure how common/useful this would be as the predicate for filtering would be limited to a discrete number of values, without getting into bespoke ways to filter by type or something.

What do you think? Does this approach seem good to you? Please clarify anything I may have misunderstood. Also happy for other ideas if you have any.

Another thing to check would be if any other GitHub actions do this type of filtering. If not maybe this functionality would be better in a standalone action.
