### ISSUE TITLE
[Feature request] Object  -> parametrize martix array (Advanced JSON Object manipulation in GitHub Actions)

### ISSUE THREAD

**Issue by sarzamas** [nickofthyme/object-remap#16]
Hi, i am new to GitHub 'Actions' and got stuck with 'strategy.matrix' dynamic parametrization...

As i understood from [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)

to arrange 'strategy.matrix' to be parametrized i should replace 'version' and 'os' values=constants in the action snippet below: 
```
...
jobs:
  example_matrix_from_DOCs:
...
    strategy:
      matrix:
        include:
          - version: 3.8
            os: ubuntu-latest
          - version: 3.10
            os: ubuntu-latest
          - version: 3.12
            os: ubuntu-latest
          - version: 3.8
            os: windows-latest
          - version: 3.10
            os: windows-latest
          - version: 3.12
            os: windows-latest
...
```
with some JSON taken from prededessor's job output: (idea is taken from [here](https://github.com/nickofthyme/object-remap?tab=readme-ov-file#argument-is-too-long))

to fullfill the task I need to introduce following approach: 
- single predecessor job generates parametrized 'matrix.include' JSON
- many followers jobs uses this JSON in 'strategy.matrix' parameter

Ex:

```
...
jobs:
  predecessor:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.save.outputs.matrix }}

    steps:
      - name:  Prepare JSON Object (**_!!! 'json=' should be replaced into 'matrix=' !!!_**)
        id: save
        uses: nickofthyme/object-remap@v2.x.x
        with:
          matrix::include: '[ 
                      [ python.${{ env.VERSION1 }}, os.${{ env.OS1 }} ],
                      [ python.${{ env.VERSION2 }}, os.${{ env.OS1 }} ],
                      [ python.${{ env.VERSION3 }}, os.${{ env.OS1 }} ],
                      [ python.${{ env.VERSION1 }}, os.${{ env.OS2 }} ],
                      [ python.${{ env.VERSION2 }}, os.${{ env.OS2 }} ],
                      [ python.${{ env.VERSION3 }}, os.${{ env.OS2 }} ]
                    ]'

  follower1:
    needs: predecessor
    strategy:
      matrix: 
          ${{ fromJSON(needs.predecessor.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
...
   steps:
...
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
...
```
OK... loooks good, but how to do it smart? ...to be honest i can't do it in any way at the moment... :(
I can't perform this flow correct nither without using your Object Remap Action nor with using it...

so may be it is right idea to share my problem here with you to extend this Object Remap Action functionality

Your Object Remap Action seems like targeting exactly what i need

**_What i have:_**  [Object Remap Action CAN GENERATE SIMPLE ARRAYS](https://github.com/nickofthyme/object-remap/blob/master/README.md#simple)
**_What i need:_**  BUT IT CAN'T GENERATE ARRAYS OF NESTED DICT:

Ex:
INPUT:
```
      - uses: nickofthyme/object-remap@v2.0.0
        with:
          include: '[ toJSON(os.[ ${{ env.OS_TYPE }} ], python.[ ${{ env.PYTHON_VERSION }} ]) ]'
```
OUTPUT:
gives following JSON as output which is **!invalid!**... in terms of 'matrix'

```
echo {
    "include": "[ toJSON(os.[ ubuntu-latest ], python.[ 3.12 ]) ]"
  }
  shell: /usr/bin/bash -e {0}
  env:
    PYTHON_VERSION: 3.12
    OS_TYPE: ubuntu-latest
(https://github.com/sarzamas/pytest_rest_example_pets/actions/runs/7172243806/job/19528988166#step:2:10)5baff4191c5.sh: line 2: include:: command not found
{
Error: Process completed with exit code 127.
```

What i expect to be usefull as feature request:
1. - to add nested array dict generation from scratch into your action facilities
2. - to accept on input the explicit __name of outputs JSON Object (default __name=json)
`echo  "'<__name>'={...}" >>  $GITHUB_OUTPUT`

P.S.
here is original code of my [CI.yaml](https://github.com/sarzamas/pytest_rest_example_pets/blob/main/.github/workflows/CI.yaml) action

I was searching for any available solution of my problem, but still use constants instead of parameters
if you could advice me how to solve my problem I would highly appreciate 
thks
sarzamas

PPS
if your action could do this matrix JSON generation EASY - i believe it will be top-used in Actions 🚀🚀🚀

**Comment by nickofthyme** [comment]
Hey @sarzamas, I'm trying to understand your specific case but I think this action could be of use.

I'll be able to better help you with a little more context. First a few comments...

GitHub workflows are a bit strange here when it comes to the [`jobs.<job_id>.strategy.matrix`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) property. My memory is not precise here but if I recall correctly, GitHub does not allow assigning [expressions](https://docs.github.com/en/actions/learn-github-actions/expressions) for enumerating the values within `jobs.<job_id>.strategy.matrix`. So in this example below, the values of `version` and `os` must be literal values, like shown here...

```yml
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
```

So this config below will **NOT** work.

```yml
jobs:
  example_matrix:
    strategy:
      matrix:
        version: ${{ fromJSON(needs.matrix_config.outputs.json.version) }} # BAD!
        os: ${{ fromJSON(needs.matrix_config.outputs.json.os) }} # BAD!
```

What you need to do instead is enumerate all the matrix options under the [`include`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude) property. BUT you also **cannot** assign an [expression](https://docs.github.com/en/actions/learn-github-actions/expressions) to this `include` property. So the below config is also bad.

```yml
jobs:
  example_matrix:
    strategy:
      matrix:
        include: ${{ fromJSON(needs.matrix_config.outputs.json.include) }} # BAD!
```

The only way to assign the matrix to an [expression](https://docs.github.com/en/actions/learn-github-actions/expressions) is to set the `matrix` property **directly**. 

Like in the example I provide [here](https://github.com/nickofthyme/object-remap/blob/master/README.md#motivation), shown below, I build the matrix array in the `fetch` job under the `save` step. Notice that the output is assigned to `include.*.number` and `include.*.sha`. That `*` syntax acts as a wildcard for array indices to spread the values into the array, effectively the inverse of [Object filters](https://docs.github.com/en/actions/learn-github-actions/expressions#object-filters). Then I assign this matrix json directly to `update-check.strategy.matrix`.

```yml
jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.save.outputs.json }}
    steps:
      - name: Get open pull requests
        id: fetch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/pulls?state=open
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create matrix
        id: save
        uses: nickofthyme/object-remap@v1
        with:
          include.*.number: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.number) }}
          include.*.sha: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.head.sha) }}

  update-check:
    name: "Checking PR #${{ matrix.number }}"
    runs-on: ubuntu-latest
    needs: fetch
    strategy:
      matrix: ${{ fromJSON(needs.fetch.outputs.matrix) }}
    steps:
      - name: Do something cool...
```

So if `steps.fetch.outputs.data` was some json like...

```json
[
  { "number": 1, "head": { "sha": "abc" }},
  { "number": 2, "head": { "sha": "def" }},
]
```

Then the output from `needs.fetch.outputs.matrix` would look something like...

```json
{
  "include": [
    { "number": 1, "sha": "abc" },
    { "number": 2, "sha": "def" },
  ]
}
```

or in `yml`

```yml
include:
  - number: 1
    sha: abc
  - number: 2
    sha: def
```

So..... This limitation of GitHub requires you to enumerate every combination of matrix options. if you had for example these options...

```yml
versions: [3.8, 3.10, 3.12]
os: [ubuntu-latest, windows-latest]
```

...you would need to loop over all of them to create all the `include` pairs then use this remap action to build the matrix json. This remap action does not support joining of these lists to generate the enumerated pairs. This does sound like an interesting idea for a new action that handles this exact use case.

Let me know if that clears things up or if you have any other questions, or if I misunderstood your use case.

**Comment by sarzamas** [comment]
hi and thanks for fast reply @nickofthyme!

yes i understand clearly following: 

- GitHub workflows are a **lot** strange when it comes to the [jobs.<job_id>.strategy.matrix] - but its anyhow possible to parametrize matrix with [matrix.include] clause...

-  in your reply you propose to add third step to parametrize matrix to get matrix parametrized... so its appeared to be paramentized

proposed scenario:
1. one additional pre-ancestor job/step creates Json with lists/emun
2. Oblect Remap Action as second stage of jobs remaps this Json
3. many followers receive this Json for matrix parametrization

I understand this all... but its too much... 🎉
my feature request concerns  - is it feasible to add functionality into Oblect Remap Action so it can generate lists from scratch?

P.S. - I rearranged  initial text in issue topic - i added clear examples of expected functionality

What i expect to be usefull as feature request:

- to add nested array of dicts generation from scratch into your action facilities
- to accept on input the explicit __name of outputs JSON Object (default __name=json)
`echo  "'<__name>'={...}" >>  $GITHUB_OUTPUT`


P.P.S - this feature request just in terms of your logo: An action designed to make object manipulation in GitHub actions just a little bit easier 🤏.

**Comment by nickofthyme** [comment]
Yes that's the proposed scenario but generating the list for `include` pairs from lists of options is not so easy in github workflow. You could do this is a `bash` or `python` script but any inputs to this scripts can be difficult to process with escaped characters and multi-lines, at least for me it was hard.

> my feature request concerns - is it feasible to add functionality into Oblect Remap Action so it can generate lists from scratch?

For this request I think it's better to keep this action functionality as is and create a simplified action that's only purpose is to generate the matrix from a list of options. For example...

```yml
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.json }}
    steps:
      - name: Create matrix
        id: matrix
        uses: nickofthyme/matrix-generator@v1
        with:
          version: [3.8, 3.10, 3.12]
          os: [ubuntu-latest, windows-latest]

  update-check:
    name: "Run for ${{ matrix.os }} ${{ matrix.version }}"
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - name: Do something cool...
```

Here the value for `needs.matrix.outputs.matrix` would simply be...

```json
{
  "include": [
    {
      "version": 3.8,
      "os": "ubuntu-latest"
    },
    {
      "version": 3.1,
      "os": "ubuntu-latest"
    },
    {
      "version": 3.12,
      "os": "ubuntu-latest"
    },
    {
      "version": 3.8,
      "os": "windows-latest"
    },
    {
      "version": 3.1,
      "os": "windows-latest"
    },
    {
      "version": 3.12,
      "os": "windows-latest"
    }
  ]
}
```

Here you could also pass an expression that is an array of expected values.

```yml
  steps:
      - name: Create matrix
        id: matrix
        uses: nickofthyme/matrix-generator@v1
        with:
          version: ${{ env.pythonVersions }}
          os: ${{ env.osList }}
```

Does that what you mean by **_from scratch_**? If this is what you meant I could create an action for you to test out and see if it suits your needs.

**Comment by sarzamas** [comment]
yes its exactly what i mean!!!

definitely i would love to experiment with this matrix-generator action

the only case i found out that 
```
    outputs:
      matrix: ${{ steps.matrix.outputs.json }} - BAD!
```

should be 
```
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }} - GOOD!
```


p.s.
i've looked into your js code - but cant help you with this task - its a bird language for me :(

**Comment by sarzamas** [comment]
i am a tester and need to manipulate rather with versions and OSes  than with pull requests filtering...

**Comment by nickofthyme** [comment]
lol yeah I was thinking the same thing about `steps.matrix.outputs.matrix`. Ok no problem, I'll try to put up a pre-release version tonight.

Are all your inputs just coming from `env` variables?

**Comment by sarzamas** [comment]
env. and inputs. context

**Comment by nickofthyme** [comment]
Ok after looking into this a little deeper it turns out I was mistaken about one **key** thing. That being when I said you cannot pass the desired dimensions to the `strategy.matrix` when in fact you can, as shown in the example [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts-to-create-matrices). I think this is a relatively new change in the past 1-2 years.

So you can actually define the matrix without the use of this remap action if you have the dimensions in the correct list (json array) form. 

```yml
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ env.python_versions }}
        os: ${{ env.os_list }}
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
```

I think this would work for your case right?

---

If you did want to build your values using the remap action that could look something like...

```yml
env:
  version: '[10, 12, 14]'
  os: '["ubuntu-latest", "windows-latest"]'

jobs:
  build-matrix:
    name: Build Matrix values
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.test.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - name: Testing usage
        id: test
        uses: nickofthyme/object-remap@v2
        with:
          os: ${{ env.os }}
          version: ${{ env.version }}
          # You can even add additional parameters with include as defined in the docs
          # See example at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude
          # include: '[{ "color": "green" }]'
      - name: Dump matrix content
        env:
          NP_MATRIX: ${{ toJson(steps.test.outputs.json) }}
        run: echo "$NP_MATRIX"

  test-matrix:
    name: "Test Action with Matrix (os: ${{ matrix.os }}, version: ${{ matrix.version }})"
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
```

Here I just generate a `matrix` json with the `os` and `version` dimensions and pass this to `strategy.matrix`. You can see this workflow run [here](https://github.com/nickofthyme/object-remap/actions/runs/7176671484/job/19541918257).

**Comment by sarzamas** [comment]
hi again
this is exactly the story:  "how i found out your Object Remap action..."

your first propoal is invalid

this snippet does not work....

```
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ env.python_versions }}
        os: ${{ env.os_list }}
```
 reason is [here](https://docs.github.com/en/actions/learn-github-actions/contexts#env-context)
it is written:
... "You can use the env context in any key in a workflow **_step_** except for the `id` and `uses` keys."

problem is following - matrix is not a step... in other words - you can't use env. context  in matrix declaration

so running 
   `matrix:
        version: ${{ env.<bla-bla-bla> }}` - gives following error:

```
[Invalid workflow file: .github/workflows/CI.yaml#L72](https://github.com/sarzamas/pytest_rest_example_pets/actions/runs/7188512012/workflow)
The workflow is not valid. .github/workflows/CI.yaml (Line: 72, Col: 17): Unrecognized named-value: 'env'. Located at position 1 within expression: env.OS_TYPE .github/workflows/CI.yaml (Line: 73, Col: 21): Unrecognized named-value: 'env'. Located at position 1 within expression: env.PYTHON_VERSION
```

just off this starting point i came to you with initial feature request...

**Comment by sarzamas** [comment]
your second proposal made my day!!!
thanks



finally i got my matrix parametrization working!!!

I've looked into your `ci.yml` and found my mistake

i declared env list parameter as: `OS_TYPE: '[ubuntu-latest]'` - BAD!
 when i start using additional quotes as: `OS_TYPE: '["ubuntu-latest"]'` - GOOD!

???who knew that???? after hiting my head into aproach mentioned in your first proposal i was almost upset out of this github actions...

...now workflow started propelling at last with matrix parametrized!

thanks again

P.S.
btw - ticket may be closed
it was my bad not knowing how to declare lists here... in env.

nevertheless - without your [object-remap](https://github.com/nickofthyme/object-remap) it wouldn't work
so i am lucky to find it 
and appreciate your help
 
P.P.S.
this additional matrix parametrization in your ci.yml should be somehow mentioned in readme

itst really awsome that i managed to parametrize matrix with your Object Remap action! - smart and easy

if you mention matrix in readme - hopefully your action will become most popular here

cause i spent a lot time to find the corect search string to find your action : `github actions fromJSON` - link to your action was 7

if people could find your action by search string `matrix-generator` - gitlab  will step  behind github

so far (without your action) there is only this [ridiculous solution](https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script) available with a lot of scripting and digging into >> $GITHUB_OUTPUT

...and just to compare how it is neat with your action
```
...
env:
  PYTHON_VERSION: '[3.10, 3.11, 3.12]'
  OS_TYPE: '["ubuntu-latest", "windows-latest", "macos-latest"]'
...
jobs:
  matrix_config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.json }}

    steps:
      - name: Prepare matrix JSON Object
        id: prepare
        uses: nickofthyme/object-remap@v2.0.0
        with:
          __case: kebab
          os: ${{ env.OS_TYPE }}
          python_version: ${{ env.PYTHON_VERSION }}
...
  someJob:
    runs-on: ${{ matrix.os }}
    needs: [ matrix_config ]

    strategy:
      matrix: ${{ fromJSON(needs.matrix_config.outputs.matrix) }}

    steps:
...
      - name: Set-Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
...
```
wish you all the best 👏👏👏👏
